// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfnhM83QGAvL7ZHnw5MuCK50ZOIZt5-w',
    appId: '1:306366643081:web:ce0ac08eea715f48153f58',
    messagingSenderId: '306366643081',
    projectId: 'booing-sports',
    authDomain: 'booing-sports.firebaseapp.com',
    storageBucket: 'booing-sports.firebasestorage.app',
    measurementId: 'G-9Q6H15J2RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqSnYDFZ4gNJ_pJQX6MIqWdA7fCvkUKs',
    appId: '1:306366643081:android:922315a75ffb0e06153f58',
    messagingSenderId: '306366643081',
    projectId: 'booing-sports',
    storageBucket: 'booing-sports.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwfnhM83QGAvL7ZHnw5MuCK50ZOIZt5-w',
    appId: '1:306366643081:web:4ea903875e666dc1153f58',
    messagingSenderId: '306366643081',
    projectId: 'booing-sports',
    authDomain: 'booing-sports.firebaseapp.com',
    storageBucket: 'booing-sports.firebasestorage.app',
    measurementId: 'G-1KGXK9SQ2P',
  );

}